# Dockerfile 04/2021
# nllab-python - basic Python environment 

FROM python:3.8.5
MAINTAINER Nadanai Laohakunakorn <nadanai.laohakunakorn@ed.ac.uk>
RUN python -m pip install pandas matplotlib scipy numpy==1.19.3 seaborn xlrd xlwt openpyxl tellurium emcee corner tqdm biocrnpyler tesbml bs4 requests lxml